### PR TITLE
:arrow_up: Update aiohttp

### PR DESCRIPTION
**Pull request by VincentRPS**
### Changes

Lets 3.7.4post0 until the last version of 3.x.x 
https://docs.aiohttp.org/en/stable/faq.html#what-is-the-api-stability-and-deprecation-policy

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

### CODE REVIEW

**Comment by Arthurdw** [comment]
I don't think we use deprecated stuff, so this should be ready for merge. Waiting for someone to test it tho.

**Comment by Lunarmagpie** [comment]
it probably works

**Comment by Endercheif** [comment]
This cannot be merged right now as it causes an error. (as caught by Scrutinizer)
`error: Could not find suitable distribution for Requirement.parse('aiohttp<3.8.0,>=3.7.4post0')`

**Review by Endercheif — APPROVED** [review]

**Comment by Lunarmagpie** [comment]
This is kinda messed up because it still has websockets. Im closing for that reason.

**Pull request closed without merging**
