### PR TITLE
🚚 Using src/ layout

### LINKED ISSUE #300: Using src Layout
didn't know what gitmoji to use since it isn't really for style as it is anything else,
https://hynek.me/articles/testing-packaging/
https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
i wouldn't know if it would be too late to use such a layout or not.

### PR DESCRIPTION
**Pull request by VincentRPS**
### Changes

Closes #300
As per my comment I will not change the layout until the current pulls changing the source are finished or new ones don’t change it too much, less then ~50 lines

 ### Check off the following

-   [ ] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

### CODE REVIEW

**Comment by Endercheif** [comment]
@RPSMain please use [gitmoji](https://gitmoji.dev)

**Comment by RPSMain** [comment]
> @RPSMain please use [gitmoji](https://gitmoji.dev)

Which one would I use?

**Comment by Endercheif** [comment]
`:truck:`
:truck:

**Comment by VincentRPS** [comment]
https://discord.com/channels/881531065859190804/881653642359345192/920514743612092437

**Pull request closed without merging**
